
version: '3.7'

networks:
  app:
    driver: bridge

services:
  githubapi:
    build:
      context: .
      dockerfile: githubapi.dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./githubapi:/home/ubuntu/githubapi/
    command: sh -c "python3 /home/ubuntu/githubapi/manage.py runserver 0.0.0.0:8080"
    container_name: githubapi
    networks:
      - app
    
  nginx:
    build:
      context: .
      dockerfile: nginx.dockerfile
    ports:
      - "80:80"
    depends_on:
      - githubapi
    networks:
      - app
  